//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CompLogin/", ConfigurationName="ServiceReference2.UserService")]
    public interface UserService {
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUsersWithAttendanceRequest", ReplyAction="http://CompLogin/UserService/getUsersWithAttendanceResponse")]
        WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse getUsersWithAttendance(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUsersWithAttendanceRequest", ReplyAction="http://CompLogin/UserService/getUsersWithAttendanceResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> getUsersWithAttendanceAsync(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersWithAttendanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersWithAttendance", Namespace="http://CompLogin/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequestBody Body;
        
        public getUsersWithAttendanceRequest() {
        }
        
        public getUsersWithAttendanceRequest(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUsersWithAttendanceRequestBody {
        
        public getUsersWithAttendanceRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersWithAttendanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersWithAttendanceResponse", Namespace="http://CompLogin/", Order=0)]
        public WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponseBody Body;
        
        public getUsersWithAttendanceResponse() {
        }
        
        public getUsersWithAttendanceResponse(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUsersWithAttendanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getUsersWithAttendanceResponseBody() {
        }
        
        public getUsersWithAttendanceResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : WindowsFormsApp1.ServiceReference2.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference2.UserService>, WindowsFormsApp1.ServiceReference2.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse WindowsFormsApp1.ServiceReference2.UserService.getUsersWithAttendance(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request) {
            return base.Channel.getUsersWithAttendance(request);
        }
        
        public string getUsersWithAttendance() {
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest inValue = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequestBody();
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUsersWithAttendance(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> WindowsFormsApp1.ServiceReference2.UserService.getUsersWithAttendanceAsync(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request) {
            return base.Channel.getUsersWithAttendanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> getUsersWithAttendanceAsync() {
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest inValue = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest();
            inValue.Body = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequestBody();
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUsersWithAttendanceAsync(inValue);
        }
    }
}
