//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CompLogin/", ConfigurationName="ServiceReference2.UserService")]
    public interface UserService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/checkInOrOutNowRequest", ReplyAction="http://CompLogin/UserService/checkInOrOutNowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse checkInOrOutNow(WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/checkInOrOutNowRequest", ReplyAction="http://CompLogin/UserService/checkInOrOutNowResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse> checkInOrOutNowAsync(WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUsersWithAttendanceRequest", ReplyAction="http://CompLogin/UserService/getUsersWithAttendanceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse getUsersWithAttendance(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUsersWithAttendanceRequest", ReplyAction="http://CompLogin/UserService/getUsersWithAttendanceResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> getUsersWithAttendanceAsync(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUserDetailsJSONRequest", ReplyAction="http://CompLogin/UserService/getUserDetailsJSONResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse getUserDetailsJSON(WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUserDetailsJSONRequest", ReplyAction="http://CompLogin/UserService/getUserDetailsJSONResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse> getUserDetailsJSONAsync(WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/breakTimeRequest", ReplyAction="http://CompLogin/UserService/breakTimeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.breakTimeResponse breakTime(WindowsFormsApp1.ServiceReference2.breakTimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/breakTimeRequest", ReplyAction="http://CompLogin/UserService/breakTimeResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.breakTimeResponse> breakTimeAsync(WindowsFormsApp1.ServiceReference2.breakTimeRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/deleteUserRequest", ReplyAction="http://CompLogin/UserService/deleteUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.deleteUserResponse deleteUser(WindowsFormsApp1.ServiceReference2.deleteUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/deleteUserRequest", ReplyAction="http://CompLogin/UserService/deleteUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.deleteUserResponse> deleteUserAsync(WindowsFormsApp1.ServiceReference2.deleteUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUserDetailsRequest", ReplyAction="http://CompLogin/UserService/getUserDetailsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.getUserDetailsResponse getUserDetails(WindowsFormsApp1.ServiceReference2.getUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getUserDetailsRequest", ReplyAction="http://CompLogin/UserService/getUserDetailsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsResponse> getUserDetailsAsync(WindowsFormsApp1.ServiceReference2.getUserDetailsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/updateUserRequest", ReplyAction="http://CompLogin/UserService/updateUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.updateUserResponse updateUser(WindowsFormsApp1.ServiceReference2.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/updateUserRequest", ReplyAction="http://CompLogin/UserService/updateUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.updateUserResponse> updateUserAsync(WindowsFormsApp1.ServiceReference2.updateUserRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/checkInOrOutCustomRequest", ReplyAction="http://CompLogin/UserService/checkInOrOutCustomResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse checkInOrOutCustom(WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/checkInOrOutCustomRequest", ReplyAction="http://CompLogin/UserService/checkInOrOutCustomResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse> checkInOrOutCustomAsync(WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getMonthlyRecordsRequest", ReplyAction="http://CompLogin/UserService/getMonthlyRecordsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse getMonthlyRecords(WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/getMonthlyRecordsRequest", ReplyAction="http://CompLogin/UserService/getMonthlyRecordsResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse> getMonthlyRecordsAsync(WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/addUserRequest", ReplyAction="http://CompLogin/UserService/addUserResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WindowsFormsApp1.ServiceReference2.addUserResponse addUser(WindowsFormsApp1.ServiceReference2.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CompLogin/UserService/addUserRequest", ReplyAction="http://CompLogin/UserService/addUserResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.addUserResponse> addUserAsync(WindowsFormsApp1.ServiceReference2.addUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkInOrOutNow", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class checkInOrOutNowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public checkInOrOutNowRequest() {
        }
        
        public checkInOrOutNowRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkInOrOutNowResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class checkInOrOutNowResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkInOrOutNowResponse() {
        }
        
        public checkInOrOutNowResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersWithAttendance", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUsersWithAttendanceRequest {
        
        public getUsersWithAttendanceRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUsersWithAttendanceResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUsersWithAttendanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getUsersWithAttendanceResponse() {
        }
        
        public getUsersWithAttendanceResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDetailsJSON", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUserDetailsJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserDetailsJSONRequest() {
        }
        
        public getUserDetailsJSONRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDetailsJSONResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUserDetailsJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getUserDetailsJSONResponse() {
        }
        
        public getUserDetailsJSONResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="breakTime", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class breakTimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public breakTimeRequest() {
        }
        
        public breakTimeRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="breakTimeResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class breakTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public breakTimeResponse() {
        }
        
        public breakTimeResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUser", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class deleteUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public deleteUserRequest() {
        }
        
        public deleteUserRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteUserResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class deleteUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public deleteUserResponse() {
        }
        
        public deleteUserResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDetails", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserDetailsRequest() {
        }
        
        public getUserDetailsRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserDetailsResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getUserDetailsResponse() {
        }
        
        public getUserDetailsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUser", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class updateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public updateUserRequest() {
        }
        
        public updateUserRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateUserResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class updateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public updateUserResponse() {
        }
        
        public updateUserResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkInOrOutCustom", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class checkInOrOutCustomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public checkInOrOutCustomRequest() {
        }
        
        public checkInOrOutCustomRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkInOrOutCustomResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class checkInOrOutCustomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public checkInOrOutCustomResponse() {
        }
        
        public checkInOrOutCustomResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMonthlyRecords", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getMonthlyRecordsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getMonthlyRecordsRequest() {
        }
        
        public getMonthlyRecordsRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMonthlyRecordsResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class getMonthlyRecordsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getMonthlyRecordsResponse() {
        }
        
        public getMonthlyRecordsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUser", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        public addUserRequest() {
        }
        
        public addUserRequest(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addUserResponse", WrapperNamespace="http://CompLogin/", IsWrapped=true)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CompLogin/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addUserResponse() {
        }
        
        public addUserResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : WindowsFormsApp1.ServiceReference2.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference2.UserService>, WindowsFormsApp1.ServiceReference2.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse WindowsFormsApp1.ServiceReference2.UserService.checkInOrOutNow(WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest request) {
            return base.Channel.checkInOrOutNow(request);
        }
        
        public string checkInOrOutNow(string arg0) {
            WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest inValue = new WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).checkInOrOutNow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse> WindowsFormsApp1.ServiceReference2.UserService.checkInOrOutNowAsync(WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest request) {
            return base.Channel.checkInOrOutNowAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutNowResponse> checkInOrOutNowAsync(string arg0) {
            WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest inValue = new WindowsFormsApp1.ServiceReference2.checkInOrOutNowRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).checkInOrOutNowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse WindowsFormsApp1.ServiceReference2.UserService.getUsersWithAttendance(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request) {
            return base.Channel.getUsersWithAttendance(request);
        }
        
        public string getUsersWithAttendance() {
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest inValue = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest();
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUsersWithAttendance(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> WindowsFormsApp1.ServiceReference2.UserService.getUsersWithAttendanceAsync(WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest request) {
            return base.Channel.getUsersWithAttendanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceResponse> getUsersWithAttendanceAsync() {
            WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest inValue = new WindowsFormsApp1.ServiceReference2.getUsersWithAttendanceRequest();
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUsersWithAttendanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse WindowsFormsApp1.ServiceReference2.UserService.getUserDetailsJSON(WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest request) {
            return base.Channel.getUserDetailsJSON(request);
        }
        
        public string getUserDetailsJSON(string arg0) {
            WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest inValue = new WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUserDetailsJSON(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse> WindowsFormsApp1.ServiceReference2.UserService.getUserDetailsJSONAsync(WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest request) {
            return base.Channel.getUserDetailsJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsJSONResponse> getUserDetailsJSONAsync(string arg0) {
            WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest inValue = new WindowsFormsApp1.ServiceReference2.getUserDetailsJSONRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUserDetailsJSONAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.breakTimeResponse WindowsFormsApp1.ServiceReference2.UserService.breakTime(WindowsFormsApp1.ServiceReference2.breakTimeRequest request) {
            return base.Channel.breakTime(request);
        }
        
        public string breakTime(string arg0) {
            WindowsFormsApp1.ServiceReference2.breakTimeRequest inValue = new WindowsFormsApp1.ServiceReference2.breakTimeRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.ServiceReference2.breakTimeResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).breakTime(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.breakTimeResponse> WindowsFormsApp1.ServiceReference2.UserService.breakTimeAsync(WindowsFormsApp1.ServiceReference2.breakTimeRequest request) {
            return base.Channel.breakTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.breakTimeResponse> breakTimeAsync(string arg0) {
            WindowsFormsApp1.ServiceReference2.breakTimeRequest inValue = new WindowsFormsApp1.ServiceReference2.breakTimeRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).breakTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.deleteUserResponse WindowsFormsApp1.ServiceReference2.UserService.deleteUser(WindowsFormsApp1.ServiceReference2.deleteUserRequest request) {
            return base.Channel.deleteUser(request);
        }
        
        public string deleteUser(string arg0) {
            WindowsFormsApp1.ServiceReference2.deleteUserRequest inValue = new WindowsFormsApp1.ServiceReference2.deleteUserRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.ServiceReference2.deleteUserResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).deleteUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.deleteUserResponse> WindowsFormsApp1.ServiceReference2.UserService.deleteUserAsync(WindowsFormsApp1.ServiceReference2.deleteUserRequest request) {
            return base.Channel.deleteUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.deleteUserResponse> deleteUserAsync(string arg0) {
            WindowsFormsApp1.ServiceReference2.deleteUserRequest inValue = new WindowsFormsApp1.ServiceReference2.deleteUserRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).deleteUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.getUserDetailsResponse WindowsFormsApp1.ServiceReference2.UserService.getUserDetails(WindowsFormsApp1.ServiceReference2.getUserDetailsRequest request) {
            return base.Channel.getUserDetails(request);
        }
        
        public string[] getUserDetails(string arg0) {
            WindowsFormsApp1.ServiceReference2.getUserDetailsRequest inValue = new WindowsFormsApp1.ServiceReference2.getUserDetailsRequest();
            inValue.arg0 = arg0;
            WindowsFormsApp1.ServiceReference2.getUserDetailsResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUserDetails(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsResponse> WindowsFormsApp1.ServiceReference2.UserService.getUserDetailsAsync(WindowsFormsApp1.ServiceReference2.getUserDetailsRequest request) {
            return base.Channel.getUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getUserDetailsResponse> getUserDetailsAsync(string arg0) {
            WindowsFormsApp1.ServiceReference2.getUserDetailsRequest inValue = new WindowsFormsApp1.ServiceReference2.getUserDetailsRequest();
            inValue.arg0 = arg0;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.updateUserResponse WindowsFormsApp1.ServiceReference2.UserService.updateUser(WindowsFormsApp1.ServiceReference2.updateUserRequest request) {
            return base.Channel.updateUser(request);
        }
        
        public string updateUser(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.updateUserRequest inValue = new WindowsFormsApp1.ServiceReference2.updateUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsFormsApp1.ServiceReference2.updateUserResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).updateUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.updateUserResponse> WindowsFormsApp1.ServiceReference2.UserService.updateUserAsync(WindowsFormsApp1.ServiceReference2.updateUserRequest request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.updateUserResponse> updateUserAsync(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.updateUserRequest inValue = new WindowsFormsApp1.ServiceReference2.updateUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).updateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse WindowsFormsApp1.ServiceReference2.UserService.checkInOrOutCustom(WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest request) {
            return base.Channel.checkInOrOutCustom(request);
        }
        
        public string checkInOrOutCustom(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest inValue = new WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).checkInOrOutCustom(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse> WindowsFormsApp1.ServiceReference2.UserService.checkInOrOutCustomAsync(WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest request) {
            return base.Channel.checkInOrOutCustomAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.checkInOrOutCustomResponse> checkInOrOutCustomAsync(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest inValue = new WindowsFormsApp1.ServiceReference2.checkInOrOutCustomRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).checkInOrOutCustomAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse WindowsFormsApp1.ServiceReference2.UserService.getMonthlyRecords(WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest request) {
            return base.Channel.getMonthlyRecords(request);
        }
        
        public string getMonthlyRecords(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest inValue = new WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getMonthlyRecords(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse> WindowsFormsApp1.ServiceReference2.UserService.getMonthlyRecordsAsync(WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest request) {
            return base.Channel.getMonthlyRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.getMonthlyRecordsResponse> getMonthlyRecordsAsync(string arg0, string arg1) {
            WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest inValue = new WindowsFormsApp1.ServiceReference2.getMonthlyRecordsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).getMonthlyRecordsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApp1.ServiceReference2.addUserResponse WindowsFormsApp1.ServiceReference2.UserService.addUser(WindowsFormsApp1.ServiceReference2.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public string addUser(string arg0, string arg1, string arg2, string arg3, string arg4) {
            WindowsFormsApp1.ServiceReference2.addUserRequest inValue = new WindowsFormsApp1.ServiceReference2.addUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            WindowsFormsApp1.ServiceReference2.addUserResponse retVal = ((WindowsFormsApp1.ServiceReference2.UserService)(this)).addUser(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.addUserResponse> WindowsFormsApp1.ServiceReference2.UserService.addUserAsync(WindowsFormsApp1.ServiceReference2.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference2.addUserResponse> addUserAsync(string arg0, string arg1, string arg2, string arg3, string arg4) {
            WindowsFormsApp1.ServiceReference2.addUserRequest inValue = new WindowsFormsApp1.ServiceReference2.addUserRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((WindowsFormsApp1.ServiceReference2.UserService)(this)).addUserAsync(inValue);
        }
    }
}
